### ISSUE TITLE
[Bug report] Segfault when saving several tabs as images

### ISSUE THREAD

**Issue by bresch** [facontidavide/PlotJuggler#161]
#### To reproduce:
- Create at least one new tab
- Click on `Tools -> Save all plot tabs as images`

#### Result:
```
Thread 1 "PlotJuggler" received signal SIGSEGV, Segmentation fault.
QString::QString (other=..., this=0x7fffffffb7a0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:878
878	{ Q_ASSERT(&other != this); d->ref.ref(); }
(gdb) backtrace
#0  QString::QString (other=..., this=0x7fffffffb7a0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:878
#1  MainWindow::on_actionSaveAllPlotTabs_triggered (this=<optimized out>) at /home/mathieu/src/PlotJuggler/plotter_gui/mainwindow.cpp:2419
#2  0x00000000004d7b3e in MainWindow::qt_static_metacall (_o=_o@entry=0x7fffffffcb60, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=58, 
    _a=_a@entry=0x7fffffffb9c0) at /home/mathieu/src/PlotJuggler/build/plotter_gui/moc_mainwindow.cpp:376
#3  0x00000000004d94e9 in MainWindow::qt_metacall (this=0x7fffffffcb60, _c=QMetaObject::InvokeMetaMethod, _id=58, _a=0x7fffffffb9c0)
    at /home/mathieu/src/PlotJuggler/build/plotter_gui/moc_mainwindow.cpp:462
#4  0x00007ffff6bb4ee0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff746f412 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
```

On branch master, SHA-1: `ce743db67b3d9638c21917e2b69f192ae647c85e`

**Comment by facontidavide** [comment]
Fixed
